### ISSUE TITLE
Crash while using camera (iOS)

### ISSUE THREAD

**Issue by Bramgus12** [Bramgus12/ProjectD#13]
When you do these steps, you get an error:
1. Open an image via camera or gallery.
2. Open the gallery or camera again.
3. cancel out of the camera or gallery.

Error: 
```
Exception has occurred.
NoSuchMethodError (NoSuchMethodError: The getter 'path' was called on null.
Receiver: null
Tried calling: path)
```

Error location:

![Error](https://i.imgur.com/cRxETJl.png)

**Comment by Bramgus12** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [1.2 afbeelding uploaden uit de galerij](https://trello.com/c/UcSGFaFp/47-12-afbeelding-uploaden-uit-de-galerij)

**Comment by ahoefnagel** [comment]
@tensopa has looked at this issue and has fixed this in a previous pull request.
